version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - cluster.name=elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1g
      restart_policy:
        condition: none

volumes:
  esdata:
